## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [45]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = http://pytorch.org/docs/stable/tensors.html

In [46]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [47]:
scalar.ndim

0

In [48]:
# Get tensor back as Python int
scalar.item()

7

In [49]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [50]:
vector.ndim

1

In [51]:
vector.shape

torch.Size([2])

In [52]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [53]:
MATRIX.ndim

2

In [54]:
MATRIX[0]

tensor([7, 8])

In [55]:
MATRIX.shape

torch.Size([2, 2])

In [56]:
# TENSOR
TENSOR =  torch.tensor([[[1, 2, 3],
                         [3, 6, 9],
                         [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [57]:
TENSOR.ndim

3

In [58]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [59]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0609, 0.7828, 0.8698, 0.8182],
        [0.8909, 0.5313, 0.9651, 0.4368],
        [0.4974, 0.0302, 0.8592, 0.2053]])

In [60]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [61]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [62]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [63]:
ones.dtype

torch.float32

In [64]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [65]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [67]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [68]:
float_32_tensor.dtype

torch.float32

In [69]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [70]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [71]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [72]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting informations from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [73]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1220, 0.7525, 0.5979, 0.8001],
        [0.8631, 0.4640, 0.2811, 0.2072],
        [0.6995, 0.5721, 0.1390, 0.5856]])

In [74]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [75]:
some_tensor.size()

torch.Size([3, 4])

In [76]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1220, 0.7525, 0.5979, 0.8001],
        [0.8631, 0.4640, 0.2811, 0.2072],
        [0.6995, 0.5721, 0.1390, 0.5856]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [77]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [78]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [79]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [80]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [81]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mutiplication

There are two main rules that performing matrix mutliplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [82]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [83]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [84]:
# Matrix multiplications by hand
1*1 + 2*2 + 3*3

14

In [85]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 291 µs, sys: 55 µs, total: 346 µs
Wall time: 355 µs


In [86]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 33 µs, sys: 0 ns, total: 33 µs
Wall time: 36.2 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [87]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

In [88]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimentions of a given tensor.

In [89]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [90]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [91]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimesions must match")
print("Output:\n")

output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimesions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [92]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [94]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [95]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [100]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [101]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [105]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [106]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of targt tensor where the minimal value occurs
x.argmin()

tensor(0)

In [107]:
x[0]

tensor(0)

In [109]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [110]:
x[9]

tensor(90)